## YAML Template.
server:
    port: 8001
    
activitiproxy:
    url:  http://localhost:8080/activiti-rest/service


      
behavior:           
    datasource:
        socketTimeout: 30000
        loginTimeout: 30000
        minimumIdle: 0
        maximumPoolSize: 50
        validationTimeout: 10000
        idleTimeout: 30000
        connectionTimeout: 30000
        autoCommit: false
        initializationFailFast: false        
        sqlserver:
            dataUrl: jdbc:mysql://127.0.0.1:3306,localhost:3306/behavior?rewriteBatchedStatements=true&useTimezone=true&serverTimezone=America/Sao_Paulo&useLegacyDatetimeCode=false         
            dataSourceUser: root
            dataSourcePassword: root
            port: 3306            
            connectionTestQuery: SELECT 1  
            
    
activiti:           
    datasource:
        socketTimeout: 30000
        loginTimeout: 30000
        minimumIdle: 0
        maximumPoolSize: 50
        validationTimeout: 10000
        idleTimeout: 30000
        connectionTimeout: 30000
        autoCommit: false
        initializationFailFast: false        
        sqlserver:
            dataUrl: jdbc:mysql://127.0.0.1:3306,localhost:3306/activiti?rewriteBatchedStatements=true&useTimezone=true&serverTimezone=America/Sao_Paulo&useLegacyDatetimeCode=false         
            dataSourceUser: root
            dataSourcePassword: root
            port: 3306            
            connectionTestQuery: SELECT 1 
            
            
email:
    host: smtp.gmail.com
    port: 587
    username: behavior47@gmail.com
    password: beh@vior2019
    auth: true  
    protocol: smtp
    starttls:
           enable: true
           required: true
           
           
           
amazonproperties:
        endpointUrl: https://s3.us-east-2.amazonaws.com
        accessKey: AKIAT4PQFE4EX2R5KXTK
        secretKey: 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
        bucketName: behint-files          
        
sftp:
    user: ftp_upload_files
    password: iP9w5tux
    host: 10.93.1.139
    port: 22
    protocol: sftp
    basePath : /uploads